### ISSUE TITLE
Network transmissions can get interrupted on shutdown

### ISSUE THREAD

**Issue by crawford** [edgebitio/enclaver#167]
When the process within an enclave sends a large amount of data over an open socket and then exits, not all of the data will be sent before the enclave exits. From the client's point of view, the response to their request is prematurely terminated. I'm guessing this is because odyn isn't flushing its buffers before exiting, but I haven't had a chance to investigate.

**Comment by eyakubovich** [comment]
Your theory sounds correct. You can see [here](https://github.com/edgebitio/enclaver/blob/main/enclaver/src/proxy/ingress.rs#L56) that it spawns a next task but doesn't store the handle and therefore doesn't join on exit. And I suppose the tokio runtime does not wait for the tasks to complete on exit.
